print('hjkl movement')
print('bwBW back/forward by token')
print('0^$ first column/first non-whitespace/end of line')
print('crtl-u ctrl-d page up/page down')
print('<line number>G goto line number')
print('HML top middle bottom of screen')
print('#* previous/next token that matches token at cursor')
print('nN repeat find ')
print("'' jump back")
print('ctrl-o ctrl-i back/forward jump list')
print('iaIA insert append')
print('oO open new line after before')
print('cwCW correct word')
print('dd delete line')
print('dt df di da correct delete')
print('s delete at cursor')
print('yy yank line')
print('yw yank word')
print('p put')
print('u ctrl-r undo redo')
print('c/d +t<char>/+f<char>/+i<char>/+a<char> correct delete ...')
